server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # serve SPA
  location / {
    try_files $uri /index.html;
  }

  # optional: proxy API calls to backend running on host (Windows Docker Desktop)
  location /api/ {
    proxy_pass http://host.docker.internal:5000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }
}